
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 01 23:25:57 CST 2025
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 21;
  public static final int DOSPUNTOS = 33;
  public static final int POR = 39;
  public static final int EXPELIARMUS = 14;
  public static final int AVADA = 8;
  public static final int RICTUSEMPRA = 16;
  public static final int DIFERENTE = 24;
  public static final int SEMI = 35;
  public static final int PARENIZQ = 29;
  public static final int HASH = 34;
  public static final int LLAVEDER = 28;
  public static final int IMPERIO = 7;
  public static final int PUNTOCOMA = 32;
  public static final int SECTUMSEMPRA = 12;
  public static final int HASTA = 19;
  public static final int ACCIO = 4;
  public static final int IGUAL = 23;
  public static final int IN = 20;
  public static final int CONFUNDO = 6;
  public static final int DIV = 40;
  public static final int PROTEGO = 13;
  public static final int NUM = 42;
  public static final int OBLIVIATE = 15;
  public static final int KEDAVRA = 9;
  public static final int ID = 41;
  public static final int WINGARDIUM = 10;
  public static final int ACCIODIVISIO = 11;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 22;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int CADENA = 43;
  public static final int MENOS = 38;
  public static final int LUMUS = 3;
  public static final int MENOR = 26;
  public static final int CRUCIO = 5;
  public static final int PARENDER = 30;
  public static final int ERROR_LEXICO = 44;
  public static final int MAYOR = 25;
  public static final int LLAVEIZQ = 27;
  public static final int ASIGN = 36;
  public static final int EXPULSO = 17;
  public static final int MAS = 37;
  public static final int BESTIA = 2;
  public static final int PORTUS = 18;
  
  
  public static String getTipoToken(int tokenID) {
    switch (tokenID) {
        case EOF: return "FIN_DE_ARCHIVO";
        case BESTIA: return "Clave Declaración"; // Asegúrate de que las mayúsculas coincidan
        case ID: return "Identificador";
        case NUM: return "Entero";
        case ASIGN: return "Operador Asignación";
        case PARENIZQ: return "Paréntesis Apertura";
        case PARENDER: return "Paréntesis Cierre";
        case PUNTOCOMA: return "Punto y Coma";
        case COMA: return "Coma";
        case HASH: return "Delimitador Final";
        case MAS: return "Operador Suma";
        default: return "TOKEN_NO_ASIGNADO";
        
    }
}

public static String getSimbolo(int tokenID) {
    // Usa una lógica similar para devolver el símbolo o lexema.
    switch (tokenID) {
        case PUNTOCOMA: return ";";
        case LLAVEIZQ: return "{";
        case PARENDER: return ")";
        case PARENIZQ: return "(";
        case COMA: return ",";
        case HASH: return "#";
        case MAS: return "+";
        default: return "";
    }
}
}

