
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 02 17:28:18 CST 2025
//----------------------------------------------------

package analizador;

import java_cup.runtime.*;
import javax.swing.JTextArea;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Oct 02 17:28:18 CST 2025
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\003\000\002\004" +
    "\002\000\002\004\004\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\006\000\002\003\006\000\002" +
    "\003\007\000\002\003\007\000\002\003\005\000\002\003" +
    "\011\000\002\003\006\000\002\005\011\000\002\017\002" +
    "\000\002\017\003\000\002\015\003\000\002\015\005\000" +
    "\002\006\007\000\002\007\006\000\002\007\010\000\002" +
    "\010\012\000\002\011\010\000\002\011\011\000\002\013" +
    "\005\000\002\012\012\000\002\012\010\000\002\014\003" +
    "\000\002\014\003\000\002\014\003\000\002\014\005\000" +
    "\002\014\005\000\002\014\005\000\002\014\005\000\002" +
    "\014\005\000\002\014\005\000\002\014\005\000\002\014" +
    "\005\000\002\014\005\000\002\014\005\000\002\016\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\030\002\uffff\004\007\005\010\007\004\011" +
    "\024\020\017\021\011\022\015\023\025\024\006\052\012" +
    "\001\002\000\012\037\036\052\035\053\034\054\037\001" +
    "\002\000\004\002\000\001\002\000\004\052\151\001\002" +
    "\000\004\052\137\001\002\000\012\037\036\052\035\053" +
    "\034\054\037\001\002\000\004\052\125\001\002\000\004" +
    "\045\113\001\002\000\032\002\ufffc\004\ufffc\005\ufffc\007" +
    "\ufffc\011\ufffc\020\ufffc\021\ufffc\022\ufffc\023\ufffc\024\ufffc" +
    "\036\ufffc\052\ufffc\001\002\000\004\002\112\001\002\000" +
    "\004\052\103\001\002\000\032\002\ufffd\004\ufffd\005\ufffd" +
    "\007\ufffd\011\ufffd\020\ufffd\021\ufffd\022\ufffd\023\ufffd\024" +
    "\ufffd\036\ufffd\052\ufffd\001\002\000\004\052\100\001\002" +
    "\000\032\002\uffff\004\007\005\010\007\004\011\024\020" +
    "\017\021\011\022\015\023\025\024\006\036\uffff\052\012" +
    "\001\002\000\032\002\ufff9\004\ufff9\005\ufff9\007\ufff9\011" +
    "\ufff9\020\ufff9\021\ufff9\022\ufff9\023\ufff9\024\ufff9\036\ufff9" +
    "\052\ufff9\001\002\000\032\002\ufffa\004\ufffa\005\ufffa\007" +
    "\ufffa\011\ufffa\020\ufffa\021\ufffa\022\ufffa\023\ufffa\024\ufffa" +
    "\036\ufffa\052\ufffa\001\002\000\032\002\ufffb\004\ufffb\005" +
    "\ufffb\007\ufffb\011\ufffb\020\ufffb\021\ufffb\022\ufffb\023\ufffb" +
    "\024\ufffb\036\ufffb\052\ufffb\001\002\000\004\052\031\001" +
    "\002\000\004\042\027\001\002\000\032\002\ufff8\004\ufff8" +
    "\005\ufff8\007\ufff8\011\ufff8\020\ufff8\021\ufff8\022\ufff8\023" +
    "\ufff8\024\ufff8\036\ufff8\052\ufff8\001\002\000\004\044\030" +
    "\001\002\000\032\002\ufff3\004\ufff3\005\ufff3\007\ufff3\011" +
    "\ufff3\020\ufff3\021\ufff3\022\ufff3\023\ufff3\024\ufff3\036\ufff3" +
    "\052\ufff3\001\002\000\006\026\033\045\032\001\002\000" +
    "\012\037\036\052\035\053\034\054\037\001\002\000\012" +
    "\037\036\052\035\053\034\054\037\001\002\000\052\010" +
    "\uffe1\012\uffe1\013\uffe1\014\uffe1\015\uffe1\016\uffe1\017\uffe1" +
    "\025\uffe1\031\uffe1\032\uffe1\033\uffe1\034\uffe1\040\uffe1\041" +
    "\uffe1\042\uffe1\043\uffe1\046\uffe1\047\uffe1\050\uffe1\051\uffe1" +
    "\001\002\000\052\010\uffe2\012\uffe2\013\uffe2\014\uffe2\015" +
    "\uffe2\016\uffe2\017\uffe2\025\uffe2\031\uffe2\032\uffe2\033\uffe2" +
    "\034\uffe2\040\uffe2\041\uffe2\042\uffe2\043\uffe2\046\uffe2\047" +
    "\uffe2\050\uffe2\051\uffe2\001\002\000\012\037\036\052\035" +
    "\053\034\054\037\001\002\000\052\010\uffe0\012\uffe0\013" +
    "\uffe0\014\uffe0\015\uffe0\016\uffe0\017\uffe0\025\uffe0\031\uffe0" +
    "\032\uffe0\033\uffe0\034\uffe0\040\uffe0\041\uffe0\042\uffe0\043" +
    "\uffe0\046\uffe0\047\uffe0\050\uffe0\051\uffe0\001\002\000\026" +
    "\012\047\013\042\014\052\015\051\016\043\043\044\046" +
    "\046\047\041\050\045\051\050\001\002\000\012\037\036" +
    "\052\035\053\034\054\037\001\002\000\012\037\036\052" +
    "\035\053\034\054\037\001\002\000\012\037\036\052\035" +
    "\053\034\054\037\001\002\000\004\035\061\001\002\000" +
    "\012\037\036\052\035\053\034\054\037\001\002\000\012" +
    "\037\036\052\035\053\034\054\037\001\002\000\012\037" +
    "\036\052\035\053\034\054\037\001\002\000\012\037\036" +
    "\052\035\053\034\054\037\001\002\000\012\037\036\052" +
    "\035\053\034\054\037\001\002\000\012\037\036\052\035" +
    "\053\034\054\037\001\002\000\052\010\uffd8\012\uffd8\013" +
    "\uffd8\014\uffd8\015\uffd8\016\uffd8\017\uffd8\025\uffd8\031\uffd8" +
    "\032\uffd8\033\uffd8\034\uffd8\040\uffd8\041\uffd8\042\uffd8\043" +
    "\uffd8\046\uffd8\047\uffd8\050\uffd8\051\uffd8\001\002\000\052" +
    "\010\uffd7\012\uffd7\013\uffd7\014\uffd7\015\uffd7\016\uffd7\017" +
    "\uffd7\025\uffd7\031\uffd7\032\uffd7\033\uffd7\034\uffd7\040\uffd7" +
    "\041\uffd7\042\uffd7\043\uffd7\046\uffd7\047\uffd7\050\uffd7\051" +
    "\uffd7\001\002\000\052\010\uffdb\012\uffdb\013\uffdb\014\uffdb" +
    "\015\uffdb\016\uffdb\017\uffdb\025\uffdb\031\uffdb\032\uffdb\033" +
    "\uffdb\034\uffdb\040\uffdb\041\uffdb\042\uffdb\043\uffdb\046\uffdb" +
    "\047\uffdb\050\uffdb\051\uffdb\001\002\000\052\010\uffda\012" +
    "\uffda\013\uffda\014\052\015\051\016\043\017\uffda\025\uffda" +
    "\031\uffda\032\uffda\033\uffda\034\uffda\040\uffda\041\uffda\042" +
    "\uffda\043\uffda\046\uffda\047\uffda\050\045\051\050\001\002" +
    "\000\052\010\uffde\012\uffde\013\uffde\014\052\015\051\016" +
    "\043\017\uffde\025\uffde\031\uffde\032\uffde\033\uffde\034\uffde" +
    "\040\uffde\041\uffde\042\uffde\043\uffde\046\uffde\047\uffde\050" +
    "\045\051\050\001\002\000\052\010\uffdc\012\uffdc\013\uffdc" +
    "\014\uffdc\015\uffdc\016\uffdc\017\uffdc\025\uffdc\031\uffdc\032" +
    "\uffdc\033\uffdc\034\uffdc\040\uffdc\041\uffdc\042\uffdc\043\uffdc" +
    "\046\uffdc\047\uffdc\050\uffdc\051\uffdc\001\002\000\030\004" +
    "\007\005\010\007\004\011\024\020\017\021\011\022\015" +
    "\023\025\024\006\036\uffff\052\012\001\002\000\032\002" +
    "\uffe3\004\uffe3\005\uffe3\007\uffe3\011\uffe3\020\uffe3\021\uffe3" +
    "\022\uffe3\023\uffe3\024\uffe3\036\uffe3\052\uffe3\001\002\000" +
    "\004\036\064\001\002\000\032\002\uffe5\004\uffe5\005\uffe5" +
    "\007\uffe5\011\uffe5\020\uffe5\021\uffe5\022\uffe5\023\uffe5\024" +
    "\uffe5\036\uffe5\052\uffe5\001\002\000\052\010\uffd6\012\uffd6" +
    "\013\uffd6\014\uffd6\015\uffd6\016\uffd6\017\uffd6\025\uffd6\031" +
    "\uffd6\032\uffd6\033\uffd6\034\uffd6\040\uffd6\041\uffd6\042\uffd6" +
    "\043\uffd6\046\uffd6\047\uffd6\050\uffd6\051\uffd6\001\002\000" +
    "\052\010\uffd9\012\uffd9\013\uffd9\014\052\015\051\016\043" +
    "\017\uffd9\025\uffd9\031\uffd9\032\uffd9\033\uffd9\034\uffd9\040" +
    "\uffd9\041\uffd9\042\uffd9\043\uffd9\046\uffd9\047\uffd9\050\045" +
    "\051\050\001\002\000\052\010\uffdd\012\uffdd\013\uffdd\014" +
    "\052\015\051\016\043\017\uffdd\025\uffdd\031\uffdd\032\uffdd" +
    "\033\uffdd\034\uffdd\040\uffdd\041\uffdd\042\uffdd\043\uffdd\046" +
    "\uffdd\047\uffdd\050\045\051\050\001\002\000\026\012\047" +
    "\013\042\014\052\015\051\016\043\040\071\046\046\047" +
    "\041\050\045\051\050\001\002\000\052\010\uffdf\012\uffdf" +
    "\013\uffdf\014\uffdf\015\uffdf\016\uffdf\017\uffdf\025\uffdf\031" +
    "\uffdf\032\uffdf\033\uffdf\034\uffdf\040\uffdf\041\uffdf\042\uffdf" +
    "\043\uffdf\046\uffdf\047\uffdf\050\uffdf\051\uffdf\001\002\000" +
    "\026\012\047\013\042\014\052\015\051\016\043\025\073" +
    "\046\046\047\041\050\045\051\050\001\002\000\012\037" +
    "\036\052\035\053\034\054\037\001\002\000\026\012\047" +
    "\013\042\014\052\015\051\016\043\043\075\046\046\047" +
    "\041\050\045\051\050\001\002\000\004\035\061\001\002" +
    "\000\032\002\uffe4\004\uffe4\005\uffe4\007\uffe4\011\uffe4\020" +
    "\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\036\uffe4\052\uffe4" +
    "\001\002\000\006\002\ufffe\036\ufffe\001\002\000\004\042" +
    "\101\001\002\000\004\044\102\001\002\000\032\002\ufff7" +
    "\004\ufff7\005\ufff7\007\ufff7\011\ufff7\020\ufff7\021\ufff7\022" +
    "\ufff7\023\ufff7\024\ufff7\036\ufff7\052\ufff7\001\002\000\006" +
    "\027\105\030\104\001\002\000\004\042\110\001\002\000" +
    "\004\042\106\001\002\000\004\044\107\001\002\000\032" +
    "\002\ufff5\004\ufff5\005\ufff5\007\ufff5\011\ufff5\020\ufff5\021" +
    "\ufff5\022\ufff5\023\ufff5\024\ufff5\036\ufff5\052\ufff5\001\002" +
    "\000\004\044\111\001\002\000\032\002\ufff4\004\ufff4\005" +
    "\ufff4\007\ufff4\011\ufff4\020\ufff4\021\ufff4\022\ufff4\023\ufff4" +
    "\024\ufff4\036\ufff4\052\ufff4\001\002\000\004\002\001\001" +
    "\002\000\014\006\114\037\036\052\035\053\034\054\037" +
    "\001\002\000\012\037\036\052\035\053\034\054\037\001" +
    "\002\000\026\012\047\013\042\014\052\015\051\016\043" +
    "\042\116\046\046\047\041\050\045\051\050\001\002\000" +
    "\004\044\117\001\002\000\032\002\uffeb\004\uffeb\005\uffeb" +
    "\007\uffeb\011\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb\024" +
    "\uffeb\036\uffeb\052\uffeb\001\002\000\026\012\047\013\042" +
    "\014\052\015\051\016\043\041\121\046\046\047\041\050" +
    "\045\051\050\001\002\000\012\037\036\052\035\053\034" +
    "\054\037\001\002\000\026\012\047\013\042\014\052\015" +
    "\051\016\043\042\123\046\046\047\041\050\045\051\050" +
    "\001\002\000\004\044\124\001\002\000\032\002\uffe8\004" +
    "\uffe8\005\uffe8\007\uffe8\011\uffe8\020\uffe8\021\uffe8\022\uffe8" +
    "\023\uffe8\024\uffe8\036\uffe8\052\uffe8\001\002\000\004\042" +
    "\126\001\002\000\004\044\127\001\002\000\032\002\ufff6" +
    "\004\ufff6\005\ufff6\007\ufff6\011\ufff6\020\ufff6\021\ufff6\022" +
    "\ufff6\023\ufff6\024\ufff6\036\ufff6\052\ufff6\001\002\000\026" +
    "\012\047\013\042\014\052\015\051\016\043\042\132\046" +
    "\131\047\041\050\045\051\050\001\002\000\012\037\036" +
    "\052\035\053\034\054\037\001\002\000\004\044\133\001" +
    "\002\000\032\002\uffea\004\uffea\005\uffea\007\uffea\011\uffea" +
    "\020\uffea\021\uffea\022\uffea\023\uffea\024\uffea\036\uffea\052" +
    "\uffea\001\002\000\026\012\uffde\013\uffde\014\052\015\051" +
    "\016\043\042\uffde\046\uffde\047\uffde\050\045\051\050\001" +
    "\002\000\004\044\136\001\002\000\032\002\uffe9\004\uffe9" +
    "\005\uffe9\007\uffe9\011\uffe9\020\uffe9\021\uffe9\022\uffe9\023" +
    "\uffe9\024\uffe9\036\uffe9\052\uffe9\001\002\000\004\037\140" +
    "\001\002\000\014\037\036\040\uffef\052\035\053\034\054" +
    "\037\001\002\000\004\040\uffee\001\002\000\004\040\146" +
    "\001\002\000\030\012\047\013\042\014\052\015\051\016" +
    "\043\040\uffed\041\144\046\046\047\041\050\045\051\050" +
    "\001\002\000\012\037\036\052\035\053\034\054\037\001" +
    "\002\000\004\040\uffec\001\002\000\004\042\147\001\002" +
    "\000\004\044\150\001\002\000\032\002\ufff0\004\ufff0\005" +
    "\ufff0\007\ufff0\011\ufff0\020\ufff0\021\ufff0\022\ufff0\023\ufff0" +
    "\024\ufff0\036\ufff0\052\ufff0\001\002\000\006\037\152\042" +
    "\153\001\002\000\014\037\036\040\uffef\052\035\053\034" +
    "\054\037\001\002\000\004\044\154\001\002\000\032\002" +
    "\ufff1\004\ufff1\005\ufff1\007\ufff1\011\ufff1\020\ufff1\021\ufff1" +
    "\022\ufff1\023\ufff1\024\ufff1\036\ufff1\052\ufff1\001\002\000" +
    "\004\040\156\001\002\000\004\042\157\001\002\000\004" +
    "\044\160\001\002\000\032\002\ufff2\004\ufff2\005\ufff2\007" +
    "\ufff2\011\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2\024\ufff2" +
    "\036\ufff2\052\ufff2\001\002\000\036\012\047\013\042\014" +
    "\052\015\051\016\043\017\165\031\166\032\167\033\164" +
    "\034\162\046\046\047\041\050\045\051\050\001\002\000" +
    "\012\037\uffd1\052\uffd1\053\uffd1\054\uffd1\001\002\000\012" +
    "\037\036\052\035\053\034\054\037\001\002\000\012\037" +
    "\uffd2\052\uffd2\053\uffd2\054\uffd2\001\002\000\012\037\uffd5" +
    "\052\uffd5\053\uffd5\054\uffd5\001\002\000\012\037\uffd4\052" +
    "\uffd4\053\uffd4\054\uffd4\001\002\000\012\037\uffd3\052\uffd3" +
    "\053\uffd3\054\uffd3\001\002\000\030\010\172\012\047\013" +
    "\042\014\052\015\051\016\043\043\171\046\046\047\041" +
    "\050\045\051\050\001\002\000\004\035\061\001\002\000" +
    "\004\043\173\001\002\000\004\035\061\001\002\000\032" +
    "\002\uffe6\004\uffe6\005\uffe6\007\uffe6\011\uffe6\020\uffe6\021" +
    "\uffe6\022\uffe6\023\uffe6\024\uffe6\036\uffe6\052\uffe6\001\002" +
    "\000\032\002\uffe7\004\uffe7\005\uffe7\007\uffe7\011\uffe7\020" +
    "\uffe7\021\uffe7\022\uffe7\023\uffe7\024\uffe7\036\uffe7\052\uffe7" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\173\000\024\002\013\003\017\004\004\005\015\006" +
    "\012\007\022\010\021\011\020\012\025\001\001\000\004" +
    "\014\160\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\014\127\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\022" +
    "\003\017\004\076\005\015\006\012\007\022\010\021\011" +
    "\020\012\025\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\071\001\001\000\004\014\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\067" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\066\001\001\000\004\014\065\001\001\000\004\014\064" +
    "\001\001\000\004\013\061\001\001\000\004\014\057\001" +
    "\001\000\004\014\056\001\001\000\004\014\055\001\001" +
    "\000\004\014\054\001\001\000\004\014\053\001\001\000" +
    "\004\014\052\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\003\017\004\062\005\015\006\012" +
    "\007\022\010\021\011\020\012\025\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\073\001\001" +
    "\000\002\001\001\000\004\013\075\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\114\001\001\000\004\014\117\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\014\121\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\133\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\014\142\015\140\017\141\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\014\142\015\144" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\014\142" +
    "\015\140\017\154\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\162\001\001\000\002\001" +
    "\001\000\004\014\167\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\013\174\001\001\000\002\001\001\000\004" +
    "\013\173\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Variable pública para que Principal.java pueda inyectar el JTextArea
    public JTextArea salidaArea; 

    public void setSalida(JTextArea area) {
        this.salidaArea = area;
    }

    public void syntax_error(Symbol s) {
        if (salidaArea != null) {
            salidaArea.append("\n>>> ERROR SINTÁCTICO <<<\n");
            salidaArea.append("Token inesperado: " + (s.value != null ? s.value : "Símbolo") + 
                              " (Línea: " + (s.left + 1) + ", Columna: " + (s.right + 1) + ")\n");
        } else {
            System.err.println("Error sintáctico: Token inesperado " + s.value + " en línea " + (s.left + 1));
        }
    }
    
    public void unrecovered_syntax_error(Symbol s) {
        report_error("Error sintáctico irrecuperable", s);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // comparador ::= MENOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // comparador ::= MAYOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // comparador ::= DIFERENTE 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // comparador ::= IGUAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // comparador ::= PROTEGO 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("comparador",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion ::= expresion SECTUMSEMPRA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= expresion ACCIODIVISIO expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion ::= expresion WINGARDIUM expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= expresion KEDAVRA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= expresion AVADA expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= expresion DIV expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= expresion POR expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= expresion MENOS expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= expresion MAS expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= PARENIZQ expresion PARENDER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= NUM 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ciclo ::= IMPERIO ID IN expresion DOSPUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ciclo",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ciclo ::= IMPERIO ID ASIGN expresion HASTA expresion DOSPUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ciclo",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // bloque ::= LLAVEIZQ sentencias LLAVEDER 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicional ::= CRUCIO expresion comparador expresion CONFUNDO DOSPUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicional",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicional ::= CRUCIO expresion comparador expresion DOSPUNTOS bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicional",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lectura ::= ID ASIGN ACCIO expresion COMA expresion PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lectura",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // impresion ::= LUMUS expresion MAS expresion PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // impresion ::= LUMUS expresion PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // asignacion ::= ID ASIGN expresion PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // parametros ::= expresion COMA parametros 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // parametros ::= expresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // opt_params ::= parametros 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_params",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // opt_params ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("opt_params",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // declaracion ::= BESTIA ID PARENIZQ opt_params PARENDER PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // sentencia ::= PORTUS ID PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencia ::= PORTUS ID PARENIZQ opt_params PARENDER PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencia ::= EXPULSO PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentencia ::= RICTUSEMPRA ID MINUSMINUS PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= RICTUSEMPRA ID PLUSPLUS PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= OBLIVIATE ID PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= EXPELIARMUS ID PUNTOCOMA HASH 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= ciclo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= condicional 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= lectura 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= impresion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= declaracion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sentencias ::= sentencia sentencias 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sentencias ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= sentencias 
            {
              Object RESULT =null;
		 
                if (parser.salidaArea != null && parser.salidaArea.getText().isEmpty()) { 
                    parser.salidaArea.append("\nAnálisis realizado correctamente\n"); 
                } 
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

